/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CTA: typeof import('./components/CTA.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    HowItWorks: typeof import('./components/HowItWorks.vue')['default']
    Pricing: typeof import('./components/Pricing.vue')['default']
    Testimonials: typeof import('./components/Testimonials.vue')['default']
  }
}
